import Head from 'next/head'
import openai from '../lib/openai'
import Button from '../components/Button'
import { useState } from 'react'
import TextInput from '../components/TextInput'
import Image from 'next/image'

export default function Home() {
  const [input, setInput] = useState<string>('')
  const [answer, setAnswer] = useState<string | null>(null)

  const answerQuestion = async () => {
    //check if input is empty
    if (!input) return
    try {
      setAnswer('Pensando...')
      //add ask to answer
      const response = await openai.createCompletion({
        model: 'text-davinci-003',
        prompt: `responda grosseiramente a pergunta, ${input}`,
        best_of: 1,
        frequency_penalty: 0,
        logprobs: 0,
        max_tokens: 256,
        presence_penalty: 0,
        stream: false,
        temperature: 0.7,
        top_p: 1,
      })

      if (!response.data.choices[0].text) return
      //remove ask from answer
      setAnswer(response.data.choices[0].text?.replace(input, ''))
    } catch (err) {
      setAnswer('Não entendi sua pergunta, tente novamente')
      console.log(err)
    }
  }

  return (
    <>
      <Head>
        <title>Chat gpt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center">
        <div className='w-1/4'>
          <div className='flex flex-col items-center mb-4 text-white space-y-1'>
            <Image src="/bongo-cat.gif" alt="Bongo Cat" />
            <span className="text-xs tracking-4 text-white/80">Totalmente não profissional</span>
            <span className=' font-bold text-3xl'>
              Bongo <span className="font-thin text-3xl">GPT</span>
            </span>
          </div>
          <TextInput
            placeholder='Digite sua pergunta'
            value={input}
            setValue={setInput}
          />
          <div>
            <Button
              text='Enviar'
              action={answerQuestion}
            />
          </div>
          {answer ?
            <div className="p-2 bg-neutral-700/20 border border-neutral-700 mt-4 rounded-xl overflow-y-scroll max-h-[175px]">
              <span className='text-white text-sm'>{answer}</span>
            </div>
            :
            <></>
          }
        </div>
      </div>
      <footer className='absolute inset-x-2 bottom-1'>
        <div>
          <span className='text-white font-medium'>Made with ❤️ by <a href="https://github.com/pivattogui" target="_blank" rel="noopener" className='text-blue-500'>@pivattogui</a></span>
        </div>
      </footer>
    </>
  )
}
